# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\UI_GeneratorMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeneratorMainWindow(object):
    def setupUi(self, GeneratorMainWindow):
        GeneratorMainWindow.setObjectName("GeneratorMainWindow")
        GeneratorMainWindow.resize(851, 617)
        GeneratorMainWindow.setIconSize(QtCore.QSize(22, 22))
        GeneratorMainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        GeneratorMainWindow.setDocumentMode(False)
        GeneratorMainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(GeneratorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        GeneratorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GeneratorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        GeneratorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GeneratorMainWindow)
        self.statusbar.setObjectName("statusbar")
        GeneratorMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(GeneratorMainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        GeneratorMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_QP = QtWidgets.QAction(GeneratorMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/new_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_QP.setIcon(icon)
        self.actionNew_QP.setObjectName("actionNew_QP")
        self.actionLoad_QP = QtWidgets.QAction(GeneratorMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_QP.setIcon(icon1)
        self.actionLoad_QP.setObjectName("actionLoad_QP")
        self.actionSave_QP = QtWidgets.QAction(GeneratorMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/save_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_QP.setIcon(icon2)
        self.actionSave_QP.setObjectName("actionSave_QP")
        self.actionSave_As = QtWidgets.QAction(GeneratorMainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(GeneratorMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(GeneratorMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGenerate = QtWidgets.QAction(GeneratorMainWindow)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionPreview = QtWidgets.QAction(GeneratorMainWindow)
        self.actionPreview.setObjectName("actionPreview")
        self.actionPreferences = QtWidgets.QAction(GeneratorMainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionPrint = QtWidgets.QAction(GeneratorMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/print_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon3)
        self.actionPrint.setObjectName("actionPrint")
        self.menuFile.addAction(self.actionNew_QP)
        self.menuFile.addAction(self.actionLoad_QP)
        self.menuFile.addAction(self.actionSave_QP)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuActions.addAction(self.actionGenerate)
        self.menuActions.addAction(self.actionPreview)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew_QP)
        self.toolBar.addAction(self.actionLoad_QP)
        self.toolBar.addAction(self.actionSave_QP)
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(GeneratorMainWindow)
        QtCore.QMetaObject.connectSlotsByName(GeneratorMainWindow)

    def retranslateUi(self, GeneratorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GeneratorMainWindow.setWindowTitle(_translate("GeneratorMainWindow", "Question Paper Generator"))
        self.menuFile.setTitle(_translate("GeneratorMainWindow", "File"))
        self.menuHelp.setTitle(_translate("GeneratorMainWindow", "Help"))
        self.menuActions.setTitle(_translate("GeneratorMainWindow", "Actions"))
        self.menuSettings.setTitle(_translate("GeneratorMainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("GeneratorMainWindow", "toolBar"))
        self.actionNew_QP.setText(_translate("GeneratorMainWindow", "New"))
        self.actionLoad_QP.setText(_translate("GeneratorMainWindow", "Load"))
        self.actionSave_QP.setText(_translate("GeneratorMainWindow", "Save"))
        self.actionSave_As.setText(_translate("GeneratorMainWindow", "Save As"))
        self.actionQuit.setText(_translate("GeneratorMainWindow", "Quit"))
        self.actionAbout.setText(_translate("GeneratorMainWindow", "About"))
        self.actionGenerate.setText(_translate("GeneratorMainWindow", "Generate into..."))
        self.actionPreview.setText(_translate("GeneratorMainWindow", "Preview"))
        self.actionPreferences.setText(_translate("GeneratorMainWindow", "Preferences"))
        self.actionPrint.setText(_translate("GeneratorMainWindow", "Print"))

import icons_rc
