# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/UI_GeneratorMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeneratorMainWindow(object):
    def setupUi(self, GeneratorMainWindow):
        GeneratorMainWindow.setObjectName("GeneratorMainWindow")
        GeneratorMainWindow.resize(851, 617)
        GeneratorMainWindow.setIconSize(QtCore.QSize(22, 22))
        GeneratorMainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        GeneratorMainWindow.setDocumentMode(False)
        GeneratorMainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(GeneratorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        GeneratorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GeneratorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        GeneratorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GeneratorMainWindow)
        self.statusbar.setObjectName("statusbar")
        GeneratorMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(GeneratorMainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        GeneratorMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_QP = QtWidgets.QAction(GeneratorMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/new_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_QP.setIcon(icon)
        self.actionNew_QP.setObjectName("actionNew_QP")
        self.actionLoad_QP = QtWidgets.QAction(GeneratorMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_QP.setIcon(icon1)
        self.actionLoad_QP.setObjectName("actionLoad_QP")
        self.actionSave_QP = QtWidgets.QAction(GeneratorMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/save_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_QP.setIcon(icon2)
        self.actionSave_QP.setObjectName("actionSave_QP")
        self.actionSave_As = QtWidgets.QAction(GeneratorMainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(GeneratorMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(GeneratorMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGenerate = QtWidgets.QAction(GeneratorMainWindow)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionPreview = QtWidgets.QAction(GeneratorMainWindow)
        self.actionPreview.setObjectName("actionPreview")
        self.actionPreferences = QtWidgets.QAction(GeneratorMainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionPrint = QtWidgets.QAction(GeneratorMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/print_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon3)
        self.actionPrint.setObjectName("actionPrint")
        self.menuFile.addAction(self.actionNew_QP)
        self.menuFile.addAction(self.actionLoad_QP)
        self.menuFile.addAction(self.actionSave_QP)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuActions.addAction(self.actionGenerate)
        self.menuActions.addAction(self.actionPreview)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew_QP)
        self.toolBar.addAction(self.actionLoad_QP)
        self.toolBar.addAction(self.actionSave_QP)
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(GeneratorMainWindow)
        QtCore.QMetaObject.connectSlotsByName(GeneratorMainWindow)

    def retranslateUi(self, GeneratorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GeneratorMainWindow.setWindowTitle(_translate("GeneratorMainWindow", "Question Paper Generator"))
        self.menuFile.setTitle(_translate("GeneratorMainWindow", "File"))
        self.menuHelp.setTitle(_translate("GeneratorMainWindow", "Help"))
        self.menuActions.setTitle(_translate("GeneratorMainWindow", "Actions"))
        self.menuSettings.setTitle(_translate("GeneratorMainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("GeneratorMainWindow", "toolBar"))
        self.actionNew_QP.setText(_translate("GeneratorMainWindow", "New"))
        self.actionLoad_QP.setText(_translate("GeneratorMainWindow", "Load"))
        self.actionSave_QP.setText(_translate("GeneratorMainWindow", "Save"))
        self.actionSave_As.setText(_translate("GeneratorMainWindow", "Save As"))
        self.actionQuit.setText(_translate("GeneratorMainWindow", "Quit"))
        self.actionAbout.setText(_translate("GeneratorMainWindow", "About"))
        self.actionGenerate.setText(_translate("GeneratorMainWindow", "Generate into..."))
        self.actionPreview.setText(_translate("GeneratorMainWindow", "Preview"))
        self.actionPreferences.setText(_translate("GeneratorMainWindow", "Preferences"))
        self.actionPrint.setText(_translate("GeneratorMainWindow", "Print"))

import icons_rc

class Ui_GeneratorWelcomeDialog(object):
    def setupUi(self, GeneratorWelcomeDialog):
        GeneratorWelcomeDialog.setObjectName("GeneratorWelcomeDialog")
        GeneratorWelcomeDialog.resize(350, 190)
        GeneratorWelcomeDialog.setMinimumSize(QtCore.QSize(400, 200))
        GeneratorWelcomeDialog.setMaximumSize(QtCore.QSize(400, 350))
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneratorWelcomeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcome_label = QtWidgets.QLabel(GeneratorWelcomeDialog)
        self.welcome_label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.welcome_label.setFont(font)
        self.welcome_label.setTextFormat(QtCore.Qt.AutoText)
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setWordWrap(False)
        self.welcome_label.setObjectName("welcome_label")
        self.verticalLayout.addWidget(self.welcome_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignBottom)
        self.openPushButton = QtWidgets.QPushButton(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPushButton.sizePolicy().hasHeightForWidth())
        self.openPushButton.setSizePolicy(sizePolicy)
        self.openPushButton.setObjectName("openPushButton")
        self.horizontalLayout.addWidget(self.openPushButton, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignBottom)
        self.label = QtWidgets.QLabel(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.label_2 = QtWidgets.QLabel(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(GeneratorWelcomeDialog)
        QtCore.QMetaObject.connectSlotsByName(GeneratorWelcomeDialog)
        self.setFixedSize(self.size())

    def retranslateUi(self, GeneratorWelcomeDialog):
        _translate = QtCore.QCoreApplication.translate
        GeneratorWelcomeDialog.setWindowTitle(_translate("GeneratorWelcomeDialog", "Welcome"))
        self.welcome_label.setText(_translate("GeneratorWelcomeDialog", "Welcome to Question Paper Generator"))
        self.pushButton_3.setText(_translate("GeneratorWelcomeDialog", "Create a new Question Paper"))
        self.openPushButton.setText(_translate("GeneratorWelcomeDialog", "Open an existing Question Paper"))
        self.pushButton.setText(_translate("GeneratorWelcomeDialog", "Settings"))
        self.label.setText(_translate("GeneratorWelcomeDialog", "Ver: 1.0.0"))
        self.label_2.setText(_translate("GeneratorWelcomeDialog", "Created by: Amit Kumar Gupta"))


class Ui_NewQPDialog(object):
    def setupUi(self, NewQPDialog):
        NewQPDialog.setObjectName("NewQPDialog")
        NewQPDialog.resize(457, 163)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewQPDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(NewQPDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.qp_path_line_edit = QtWidgets.QLineEdit(NewQPDialog)
        self.qp_path_line_edit.setObjectName("qp_path_line_edit")
        self.horizontalLayout.addWidget(self.qp_path_line_edit)
        self.qp_path_tool_button = QtWidgets.QToolButton(NewQPDialog)
        self.qp_path_tool_button.setObjectName("qp_path_tool_button")
        self.horizontalLayout.addWidget(self.qp_path_tool_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(NewQPDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.qp_filename_line_edit = QtWidgets.QLineEdit(NewQPDialog)
        self.qp_filename_line_edit.setObjectName("qp_filename_line_edit")
        self.horizontalLayout_2.addWidget(self.qp_filename_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cancel_push_button = QtWidgets.QPushButton(NewQPDialog)
        self.cancel_push_button.setObjectName("cancel_push_button")
        self.horizontalLayout_3.addWidget(self.cancel_push_button)
        self.create_qp_push_button = QtWidgets.QPushButton(NewQPDialog)
        self.create_qp_push_button.setObjectName("create_qp_push_button")
        self.horizontalLayout_3.addWidget(self.create_qp_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(NewQPDialog)
        QtCore.QMetaObject.connectSlotsByName(NewQPDialog)

    def retranslateUi(self, NewQPDialog):
        _translate = QtCore.QCoreApplication.translate
        NewQPDialog.setWindowTitle(_translate("NewQPDialog", "Create new QP"))
        self.label.setText(_translate("NewQPDialog", "Path of Question Paper: "))
        self.qp_path_tool_button.setText(_translate("NewQPDialog", "..."))
        self.label_2.setText(_translate("NewQPDialog", "Question Paper File name (.qp):"))
        self.cancel_push_button.setText(_translate("NewQPDialog", "Cancel"))
        self.create_qp_push_button.setText(_translate("NewQPDialog", "Create Question Paper"))
