# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/UI_GeneratorMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeneratorMainWindow(object):
    def setupUi(self, GeneratorMainWindow):
        GeneratorMainWindow.setObjectName("GeneratorMainWindow")
        GeneratorMainWindow.resize(851, 617)
        self.centralwidget = QtWidgets.QWidget(GeneratorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        GeneratorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GeneratorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        GeneratorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GeneratorMainWindow)
        self.statusbar.setObjectName("statusbar")
        GeneratorMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(GeneratorMainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        GeneratorMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        GeneratorMainWindow.insertToolBarBreak(self.toolBar)
        self.actionNew_QP = QtWidgets.QAction(GeneratorMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/new_qp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_QP.setIcon(icon)
        self.actionNew_QP.setObjectName("actionNew_QP")
        self.actionLoad_QP = QtWidgets.QAction(GeneratorMainWindow)
        self.actionLoad_QP.setObjectName("actionLoad_QP")
        self.actionSave_QP = QtWidgets.QAction(GeneratorMainWindow)
        self.actionSave_QP.setObjectName("actionSave_QP")
        self.actionSave_As = QtWidgets.QAction(GeneratorMainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(GeneratorMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(GeneratorMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGenerate = QtWidgets.QAction(GeneratorMainWindow)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionPreview = QtWidgets.QAction(GeneratorMainWindow)
        self.actionPreview.setObjectName("actionPreview")
        self.actionPreferences = QtWidgets.QAction(GeneratorMainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionNew_QP)
        self.menuFile.addAction(self.actionLoad_QP)
        self.menuFile.addAction(self.actionSave_QP)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuActions.addAction(self.actionGenerate)
        self.menuActions.addAction(self.actionPreview)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew_QP)

        self.retranslateUi(GeneratorMainWindow)
        QtCore.QMetaObject.connectSlotsByName(GeneratorMainWindow)

    def retranslateUi(self, GeneratorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GeneratorMainWindow.setWindowTitle(_translate("GeneratorMainWindow", "Question Paper Generator"))
        self.menuFile.setTitle(_translate("GeneratorMainWindow", "File"))
        self.menuHelp.setTitle(_translate("GeneratorMainWindow", "Help"))
        self.menuActions.setTitle(_translate("GeneratorMainWindow", "Actions"))
        self.menuSettings.setTitle(_translate("GeneratorMainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("GeneratorMainWindow", "toolBar"))
        self.actionNew_QP.setText(_translate("GeneratorMainWindow", "New"))
        self.actionLoad_QP.setText(_translate("GeneratorMainWindow", "Load"))
        self.actionSave_QP.setText(_translate("GeneratorMainWindow", "Save"))
        self.actionSave_As.setText(_translate("GeneratorMainWindow", "Save As"))
        self.actionQuit.setText(_translate("GeneratorMainWindow", "Quit"))
        self.actionAbout.setText(_translate("GeneratorMainWindow", "About"))
        self.actionGenerate.setText(_translate("GeneratorMainWindow", "Generate into..."))
        self.actionPreview.setText(_translate("GeneratorMainWindow", "Preview"))
        self.actionPreferences.setText(_translate("GeneratorMainWindow", "Preferences"))

import icons_rc

class Ui_GeneratorWelcomeDialog(object):
    def setupUi(self, GeneratorWelcomeDialog):
        GeneratorWelcomeDialog.setObjectName("GeneratorWelcomeDialog")
        GeneratorWelcomeDialog.resize(350, 190)
        GeneratorWelcomeDialog.setMinimumSize(QtCore.QSize(350, 190))
        GeneratorWelcomeDialog.setMaximumSize(QtCore.QSize(400, 350))
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneratorWelcomeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcome_label = QtWidgets.QLabel(GeneratorWelcomeDialog)
        self.welcome_label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.welcome_label.setFont(font)
        self.welcome_label.setTextFormat(QtCore.Qt.AutoText)
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setWordWrap(False)
        self.welcome_label.setObjectName("welcome_label")
        self.verticalLayout.addWidget(self.welcome_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignBottom)
        self.openPushButton = QtWidgets.QPushButton(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPushButton.sizePolicy().hasHeightForWidth())
        self.openPushButton.setSizePolicy(sizePolicy)
        self.openPushButton.setObjectName("openPushButton")
        self.horizontalLayout.addWidget(self.openPushButton, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignBottom)
        self.label = QtWidgets.QLabel(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.label_2 = QtWidgets.QLabel(GeneratorWelcomeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(GeneratorWelcomeDialog)
        QtCore.QMetaObject.connectSlotsByName(GeneratorWelcomeDialog)

    def retranslateUi(self, GeneratorWelcomeDialog):
        _translate = QtCore.QCoreApplication.translate
        GeneratorWelcomeDialog.setWindowTitle(_translate("GeneratorWelcomeDialog", "Welcome"))
        self.welcome_label.setText(_translate("GeneratorWelcomeDialog", "Welcome to Question Paper Generator"))
        self.pushButton_3.setText(_translate("GeneratorWelcomeDialog", "Create a new Question Paper"))
        self.openPushButton.setText(_translate("GeneratorWelcomeDialog", "Open an existing Question Paper"))
        self.pushButton.setText(_translate("GeneratorWelcomeDialog", "Settings"))
        self.label.setText(_translate("GeneratorWelcomeDialog", "Ver: 1.0.0"))
        self.label_2.setText(_translate("GeneratorWelcomeDialog", "Created by: Amit Kumar Gupta"))

